---
location_name: default_location_name
template_version: '1'
apm_datamodel_space: default_apm_datamodel_space
location_app_data_dataset: default_location_app_data_dataset
location_source_data_dataset: default_location_source_data_dataset


# admin role
checklist_admin_role_name: default_checklist_admin_role_name
infield_location_checklist_admin_users_source_id: [infield_location_checklist_admin_users_source_id]

# normal role
normal_role_name: default_normal_role_name
infield_location_normal_users_source_id: [infield_location_normal_users_source_id]

# template admin role
template_admin_role_name: default_template_admin_role_name
infield_location_template_admin_users_source_id: [infield_location_template_admin_users_source_id]

# viewer role
viewer_role_name: default_viewer_role_name
infield_location_viewer_users_source_id: [infield_location_viewer_users_source_id]
