appDataSpaceId: cognite_app_data
appDataSpaceVersion: '1'
customerDataSpaceId: APM_SourceData
customerDataSpaceVersion: '1'
externalId: default-infield-config-minimal
featureConfiguration:
  accessConfiguration:
    accessGroups: []
    requireGroupMembership: false
  activityOperationSyncConfiguration:
    enabled: true
    phasesToSync:
    - Exe
  assetPageConfiguration:
    documentCard:
      description: ''
      title: name
    propertyCard:
      highlightedProperties:
      - SERIAL NUMBER
      - EQUIPMENT/LINE NUMBER
      - PART NUMBER
      - LOCATION (FACILITY AREA CODE)
      - FIRE AREA
      linkableAssetKeys:
      - ''
  cabinetConfiguration:
    enablePlanAnalysis: true
    enableResourceAllocation: true
  canvasConfiguration:
    enableIsolationBoundaries: true
  copilot:
    enabled: false
  defaultViewConfiguration:
    defaultLens: GANTT
  directPlanningConfiguration:
    activitySideEffects: []
    addActivityModalConfig:
      fields:
      - field: title
        title: Description
        type: FREE_TEXT
      - field: startDate
        hasMilestone: true
        type: DATE_TIME
      - field: functionalLocation
        type: FUNCTIONAL_LOCATION
      - field: resource
        type: SEARCH_OPTION
      - field: plannerGroup
        type: SEARCH_OPTION
      - field: type
        type: SEARCH_OPTION
      - field: cost
        type: FREE_TEXT
  disciplines:
  - externalId: 4b4a9ad5-4ed0-4c3b-b85c-13f396c4a566
    name: Mechanical
  documents:
    description: metadata.document:title
    title: name
    type: metadata.type
  enableCustomLayouts: true
  gridZones2dConfiguration:
    enabled: false
  inspectorConfiguration:
    inspectorAssetFields:
      parentExternalId:
        alias: Parent
  markerTypeConfiguration:
    markerTypes:
    - markerType: Risk
  notifications:
    overviewCard:
      filters:
        type:
        - externalId: 456a7132-6853-4e5f-80f3-428af87b2a91
          value: m4
  observations:
    enabled: true
    sapWriteBack:
      enabled: false
  planConfiguration:
    planTagsToEnableOptimisation:
    - iap
    tags:
    - label: IAP
      value: iap
    - label: Campaigns
      value: campaigns
    - label: Chores
      value: chores
    - label: E&C
      value: e_and_c
  psnConfiguration:
    disabled: true
  rootLocationConfigurations:
  - appDataInstanceSpace: cognite_app_data
    assetExternalId: {{root_asset_external_id}}
    sourceDataInstanceSpace: APM_SourceData
    templateAdmins: []
    threeDConfiguration:
      fullWeightModels: []
      lightWeightModel: {}
  subactivitiesConfiguration:
    activityPhasesFieldName: allPhases
    activityTradesFieldName: allTrades
    enabled: true
    tradeFieldName: resource
  timezoneConfiguration:
    dateFormat: DD/MM/YYYY
    dateTimeFormat: DD/MM/YYYY HH:mm
    startOfWeek: 1
