appDataSpaceId: 'APM_Config'
appDataSpaceVersion: '1'
customerDataSpaceId: APM_SourceData
customerDataSpaceVersion: '1'
externalId: default_infield_config_minimal
featureConfiguration: 
  - accessConfiguration:
      accessGroups: []
      requireGroupMembership: false