---
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --line-length=120
          - --ignore=E731,E501,W605,T201,UP007
            # See https://beta.ruff.rs/docs/rules for an overview of ruff rules
          - --select=E,W,F,I,T,RUF,TID,UP
          - --fixable=E,W,F,I,T,RUF,TID,UP
          - --target-version=py39
          - --exclude=cognite/client/_proto,cognite/client/_proto_legacy
    rev: v0.1.7

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^cognite/client/_proto.*$
        args:
          - --line-length=120
          - --target-version=py38
          - --target-version=py39
          - --target-version=py310
          - --target-version=py311
          - --include=\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: debug-statements
      - id: check-docstring-first

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.6.1'
  #   hooks:
  #     - id: mypy
  #       args: [--strict]

