cdf_cluster: ${CDF_CLUSTER}
cdf_template_version: 0.0.1
# The demo_* configs are used for demo_* packages. If you want to use a demo package to
# provision your own project, the demo_* configurations below must be changed.
# Please note that these configs are set globally for simple access. When
# developing your own modules, you should keep module configurations in the module directory.
demo_readwrite_source_id: 7df143fd-0082-4251-95c3-aebd80992d81
demo_readonly_source_id: 7df143fd-0082-4251-95c3-aebd80992d81
