apm_simple_:
  raw_db: tutorial_apm
  data_model: tutorial_apm_simple
  space: tutorial_apm_simple
  data_set: Valhall_System_23
  data_set_desc: Valhall_System_23
  datamodel_version: "1"
  view_Asset_version: "1"
  view_WorkOrder_version: "1"
  view_WorkItem_version: "1"
cdf_cluster: ${CDF_CLUSTER}
