externalId: '{{datamodel}}'
name: '{{datamodel}}'
space: '{{space}}'
version: '{{datamodel_version}}'
views:
- externalId: Pump
  space: '{{space}}'
  type: view
  version: '{{view_Pump_version}}'
- externalId: LiftStation
  space: '{{space}}'
  type: view
  version: '{{view_LiftStation_version}}'
