---
location_name: default
module_version: '1'

location_name: <change_me> # eksempel: valhall, all
source_name: <change_me>  # eksempel: sharepoint


file_location_extractor_group_source_id: <change_me> 
file_location_processing_group_source_id: <change_me>