externalId: '{{datamodel}}'
name: '{{datamodel}}'
space: '{{space}}'
version: '{{datamodel_version}}'
views:
- externalId: Asset
  space: '{{space}}'
  type: view
  version: 8069f1498c7f9a
- externalId: WorkOrder
  space: '{{space}}'
  type: view
  version: 659c59a4a8afe9
- externalId: WorkItem
  space: '{{space}}'
  type: view
  version: 94d2b7121128a2
