externalId: 'fu_context_files-{{location_name}}_{{source_name}}_annotation'
name: 'context_files-{{location_name}}_{{source_name}}_annotation'
dataSetExternalId: 'ds_files_{{location_name}}'
deploymentClientId: {{clientId}}
deploymentClientSecret: {{clientSecret}}
schedulesClientId: {{clientId}}
schedulesClientSecret: {{clientSecret}}
common_folder: common
description: "Contextualization of P&ID files creating annotations"
cpu: 0.60
memory: 2.00
metadata:
  version: "1.0.0"
