# Only valid for this module, loads template variables from environment
# RAW DB name structure: <data type>_<location>_<source>  ( see README for name standard)
# 
# In the example below we are setting up a project based on the Open Industry Data (OID), 
# that originates from the Valhall oil rig. Hence the example location below is oid
#
raw_db_asset: asset_oid_workmate
raw_db_workorder: workorder_oid_workmate
raw_db_files: files_oid_fileshare
raw_db_timeseries: timeseries_oid_pi
