# This is the configuration file used for the data realted to asset data modeling 
---
# spesify the site/asset location where data comes from, ex 'valhall' or if they are generic for all assets use 'all' 
location_name: <update-me> 
module_version: '1'

# spesify the name of the source making it possible to identify where the data orginates from, ex: 'workmate', 'sap', 'oracle',..
source_name: <update-me>

asset_dataset: <update-me> # ex: ds_asset_valhall
asset_raw_input_dp: <update-me> # ex: src-asset-valhall-workmate
asset_raw_input_table: <update-me> # ex: assets

# source ID from Azure AD for the corresponding groups, ex 'c74797ce-9191-4a4a-9186-8fe21c54c3de'
asset_location_extractor_group_source_id: <update-me>
asset_location_processing_group_source_id: <update-me>
asset_location_read_group_source_id: <update-me>


# Transformation credentials
clientId: ${IDP_CLIENT_ID}
clientSecret: ${IDP_CLIENT_SECRET}
tokenUri: ${IDP_TOKEN_URL}
# Optional: If idP requires providing the scopes
cdfProjectName: ${CDF_PROJECT}
scopes: ${IDP_SCOPES}
# Optional: If idP requires providing the audience
audience: ${IDP_AUDIENCE}

