# Only valid for this module, loads template variables from environment
model_space: sp_ExtendedSourceDataModels
instance_space: sp_cdfTemplateInstances
view_asset_version: '1'
data_model_version: '1'
root_asset_external_id: 'lift_pump_stations:root'
