# This is the configuration file used for the example data from The Open Industrial Data (oid)
#
# The data originates from a single compressor on Aker BP’s Valhall oil platform 
# in the North Sea. Aker BP selected the first stage compressor on the Valhall 
# because it is a subsystem with clearly defined boundaries, rich in time series and maintenance data.
# spesify the site/asset location where data comes from, ex 'valhall_oid' or if they are generic for all assets use 'all' 

# location based on OID example data
location_name: oid

# spesify the name of the source making it possible to identify where the data orginates from, ex: 'workmate', 'sap', 'oracle',..
source_name: workmate
asset_dataset: ds_asset_oid
asset_raw_input_db: asset_oid_workmate
asset_raw_input_table: assets
pause_transformations: true
