# Only valid for this module, loads template variables from environment
model_space: sp_pumpModelSpace
instance_space: sp_pumpInstanceSpace
source_model_space: sp_ExtendedSourceDataModels
source_model: ExtendedSourceData
view_Pump_version: "1"
view_LiftStation_version: "1"
data_model_version: "1"
data_model: "PumpLiftStations"
