# Values here are only valid for this module.
# The raw database values here point to the RAW data loaded in the cdf_oid_example_data
# module. If you have changed the default values in that module, you need to change them here as well.
asset_raw_db: asset_oid_workmate
workorder_raw_db: workorder_oid_workmate
files_raw_db: files_oid_fileshare
datamodel: apm_simple
space: apm_simple
datamodel_version: '1'
view_Asset_version: '1'
view_WorkOrder_version: '1'
view_WorkItem_version: '1'
# In addition, the transformations are using the following variables from the global scope (your root default.config.yaml):
#cicd_clientId
#cicd_clientSecret
#cicd_tokenUri
#cdfProjectName
#cicd_scopes
#cicd_audience