# Only valid for this module, loads template variables from environment
# The raw database values here point to the RAW data loaded in the cdf_oid_example_data
# module. 
assets_raw_db: workmate_assets
workorders_raw_db: workmate_workorders
files_raw_db: fileshare_files
datamodel: apm_simple
space: apm_simple
datamodel_version: '1'
view_Asset_version: '1'
view_WorkOrder_version: '1'
view_WorkItem_version: '1'
# In addition, the transformations are using the following variables from the global scope (your root default.config.yaml):
#cicd_clientId
#cicd_clientSecret
#cicd_tokenUri
#cdfProjectName
#cicd_scopes
#cicd_audience