name: 'applications-configuration'
sourceId: '{{applicationsconfiguration_source_id}}'
metadata:
  origin: 'cdf-project-templates'
capabilities:
  - groupsAcl:
      actions:
        - LIST
        - READ
      scope:
        currentuserscope: {}
  - threedAcl:
      actions:
        - READ
      scope:
        all: {}
  - assetsAcl:
      actions:
        - READ
      scope:
        all: {}
  - dataModelsAcl:
      actions:
        - READ
      scope:
        all: {}
  - dataModelInstancesAcl:
      actions:
        - READ
      scope:
        all: {}
  - dataModelInstancesAcl:
      actions:
        - WRITE
      scope:
        spaceIdScope: {spaceIds: ['cognite_app_data', 'APM_Config']}
  - datasetsAcl:
      actions:
        - READ
      scope:
        all: {}
