cognite_modules:
  cdfProjectName: ${CDF_PROJECT}
  cdf_cluster: ${CDF_CLUSTER}
  cicd_audience: ${IDP_AUDIENCE}
  cicd_clientId: ${IDP_CLIENT_ID}
  cicd_clientSecret: ${IDP_CLIENT_SECRET}
  cicd_scopes:
  - ${IDP_SCOPES}
# Optional: If idP requires providing the audience
  cicd_tokenUri: ${IDP_TOKEN_URL}
  scheduleDaily: 35 1 * * *
  scheduleHourly: 7 * * * *
  scheduleQuarterly: 0/15 * * * *
  common:
    cdf_auth_readwrite_all:
      readonly_source_id: <change_me>
      readwrite_source_id: <change_me>
  core:
    cdf_apm_base:
      apm_datamodel_space: APM_SourceData
      apm_datamodel_version: '1'
  examples:
    cdf_apm_simple_data_model:
      datamodel: apm_simple
      datamodel_version: '1'
      default_location: oid
      pause_transformations: true
      source_asset: workmate
      source_timeseries: pi
      source_workorder: workmate
      space: apm_simple
      view_Asset_version: '1'
      view_WorkItem_version: '1'
      view_WorkOrder_version: '1'
    cdf_oid_example_data:
      default_location: oid
      source_asset: workmate
      source_files: fileshare
      source_timeseries: pi
      source_workorder: workmate
    example_pump_asset_hierarchy:
      data_set: src:lift_pump_stations
      raw_db: pump_assets
  experimental:
    cdf_asset_source_model:
      data_model_version: '1'
      instance_space: cdfTemplateInstances
      model_space: ExtendedSourceDataModels
      root_asset_external_id: lift_pump_stations:root
      view_asset_version: '1'
    example_pump_data_model:
      data_model: PumpLiftStations
      data_model_version: '1'
      instance_space: pumpInstanceSpace
      model_space: pumpModelSpace
      source_model: ExtendedSourceData
      source_model_space: ExtendedSourceDataModels
      view_LiftStation_version: '1'
      view_Pump_version: '1'
  infield:
    cdf_infield_common:
      applicationsconfiguration_source_id: <change_me>
    cdf_infield_location:
      apm_app_config_external_id: default-infield-config-minimal
      apm_config_instance_space: APM_Config
      apm_datamodel_space: APM_SourceData
      default_location: oid
      infield_default_location_checklist_admin_users_source_id: <change_me>
      infield_default_location_normal_users_source_id: <change_me>
      infield_default_location_template_admin_users_source_id: <change_me>
      infield_default_location_viewer_users_source_id: <change_me>
      module_version: '1'
      root_asset_external_id: WMT:VAL
      source_asset: workmate
      source_workorder: workmate
      workorder_raw_db: workorder_oid_workmate
      workorder_table_name: workorders
custom_modules:
  my_example_module:
    example_variable: demo_dataset
