# Only valid for this module, loads template variables from environment
model_space: ExtendedSourceDataModels
instance_space: cdfTemplateInstances
view_asset_version: '1'
data_model_version: '1'
root_asset_external_id: 'lift_pump_stations:root'
clientId: ${IDP_CLIENT_ID}
clientSecret: ${IDP_CLIENT_SECRET}
tokenUri: ${IDP_TOKEN_URL}
# Optional: If idP requires providing the scopes
cdfProjectName: ${CDF_PROJECT}
scopes:
  - ${IDP_SCOPES}
# Optional: If idP requires providing the audience
audience: ${IDP_AUDIENCE}
