# Only valid for this module, loads template variables from environment
view_Pump_version: "1"
view_LiftStation_version: "1"
view_Asset_version: "2"
datamodel_version: "1"
datamodel: "PumpLiftStations"
clientId: ${IDP_CLIENT_ID}
clientSecret: ${IDP_CLIENT_SECRET}
tokenUrl: ${IDP_TOKEN_URL}
# Optional: If idP requires providing the scopes
cdfProjectName: ${CDF_PROJECT}
scopes:
  - ${IDP_SCOPES}
# Optional: If idP requires providing the audience
audience: ${IDP_AUDIENCE}
