name: 'applications-configuration'
source_id: '{{demo_readonly_source_id}}'
metadata:
  origin: 'cdf-project-templates'
  cdf_template_version: '{{cdf_template_version}}'
capabilities:
  - groupsAcl:
      actions:
        - READ
        - LIST
      scope:
        all: {}
  - threedAcl:
      actions:
        - READ
      scope:
        all: {}
  - assetsAcl:
      actions:
        - READ
      scope:
        all: {}