externalId: '{{apm_simple_datamodel}}'
name: '{{apm_simple_datamodel}}'
space: '{{apm_simple_space}}'
version: '1'
views:
- externalId: Asset
  space: '{{apm_simple_space}}'
  type: view
  version: 8069f1498c7f9a
- externalId: WorkOrder
  space: '{{apm_simple_space}}'
  type: view
  version: 659c59a4a8afe9
- externalId: WorkItem
  space: '{{apm_simple_space}}'
  type: view
  version: 94d2b7121128a2
