environment:
  common_function_code: ./common_function_code
  name: dev
  project: <customer-dev>
  selected:
  - cognite_modules/
  - custom_modules/
  type: dev
variables:
  cognite_modules:
    cdfProjectName: ${CDF_PROJECT}
    cdf_cluster: ${CDF_CLUSTER}
    cicd_audience: ${IDP_AUDIENCE}
    cicd_clientId: ${IDP_CLIENT_ID}
    cicd_clientSecret: ${IDP_CLIENT_SECRET}
    cicd_scopes:
    - ${IDP_SCOPES}
    cicd_tokenUri: ${IDP_TOKEN_URL}
    common:
      cdf_auth_readwrite_all:
        readonly_source_id: <change_me>
        readwrite_source_id: <change_me>
    core:
      cdf_apm_base:
        apm_datamodel_space: APM_SourceData
        apm_datamodel_version: '1'
    examples:
      cdf_apm_simple_data_model:
        datamodel: apm_simple
        datamodel_version: '1'
        default_location: oid
        pause_transformations: true
        source_asset: workmate
        source_timeseries: pi
        source_workorder: workmate
        space: sp_apm_simple
        view_Asset_version: '1'
        view_WorkItem_version: '1'
        view_WorkOrder_version: '1'
      cdf_data_pipeline_asset_valhall:
        asset_dataset: ds_asset_oid
        asset_location_extractor_group_source_id: <change_me>
        asset_location_processing_group_source_id: <change_me>
        asset_location_read_group_source_id: <change_me>
        asset_raw_input_db: asset_oid_workmate
        asset_raw_input_table: assets
        location_name: oid
        pause_transformations: true
        source_name: workmate
      cdf_data_pipeline_files_valhall:
        files_dataset: ds_files_oid
        files_location_extractor_group_source_id: <change_me>
        files_location_processing_group_source_id: <change_me>
        files_location_read_group_source_id: <change_me>
        files_raw_input_db: files_oid_fileshare
        files_raw_input_table: files_metadata
        location_name: oid
        pause_transformations: true
        source_name: fileshare
        version: 0.0.1
      cdf_functions_dummy:
        default_location: oid
        example_secret: ${MY_SECRET}
        version: 0.0.1
      cdf_oid_example_data:
        default_location: oid
        source_asset: workmate
        source_files: fileshare
        source_timeseries: pi
        source_workorder: workmate
      example_pump_asset_hierarchy:
        data_set: src:lift_pump_stations
        raw_db: pump_assets
    experimental:
      cdf_asset_source_model:
        data_model_version: '1'
        data_set: ds_example_asset_source_data
        instance_space: sp_cdf_template_instances
        model_space: sp_extended_source_data_models
        root_asset_external_id: lift_pump_stations:root
        view_asset_version: '1'
      example_pump_data_model:
        data_model: PumpLiftStations
        data_model_version: '1'
        data_set: ds_example_pump_data
        instance_space: sp_pump_instance_space
        model_space: sp_pump_model_space
        source_model: ExtendedSourceData
        source_model_space: sp_extended_source_data_models
        view_LiftStation_version: '1'
        view_Pump_version: '1'
    infield:
      cdf_infield_common:
        apm_config_instance_space: APM_Config
        applicationsconfiguration_source_id: <change_me>
      cdf_infield_location:
        apm_app_config_external_id: default-infield-config-minimal
        apm_datamodel_space: APM_SourceData
        infield_location_checklist_admin_users_source_id: <change_me>
        infield_location_normal_users_source_id: <change_me>
        infield_location_template_admin_users_source_id: <change_me>
        infield_location_viewer_users_source_id: <change_me>
        module_version: '1'
        source_asset: workmate
        source_workorder: workmate
        workorder_raw_db: workorder_oid_workmate
        workorder_table_name: workorders
      cdf_infield_second_location:
        apm_app_config_external_id: default-infield-config-minimal
        apm_datamodel_space: APM_SourceData
        infield_location_checklist_admin_users_source_id: <change_me>
        infield_location_normal_users_source_id: <change_me>
        infield_location_template_admin_users_source_id: <change_me>
        infield_location_viewer_users_source_id: <change_me>
        module_version: '1'
        source_asset: workmate
        source_workorder: workmate
        workorder_raw_db: workorder_oid_workmate
        workorder_table_name: workorders
      first_location: oid
      first_root_asset_external_id: WMT:VAL
      second_location: oid2
      second_root_asset_external_id: WMT:VAL
    scheduleDaily: 35 1 * * *
    scheduleHourly: 7 * * * *
    scheduleQuarterly: 0/15 * * * *
  custom_modules:
    my_example_module:
      example_variable: <Not Set>
