---
name: build
on:
  pull_request:
    branches: [main]
env:
  PYTHON_VERSION: '3.11'
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
            version: 1.6.1
            virtualenvs-create: false
      - name: Install dependencies and run lints
        run: |
          # Necessary for running the mypy pre-commit hook
          poetry install
      - uses: pre-commit/action@v3.0.0
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: false
      - name: Install core dependencies
        run: |
          poetry install
      - name: Run pytest
        run: pytest tests
