name: Deploy modules

on:
    push:
        branches:
            - ghactions

jobs:

    build-modules:
        runs-on: ubuntu-latest
        name: Loadmaster
        steps:
            - uses: actions/checkout@v4
      
            - uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - uses: snok/install-poetry@v1
              with:
                version: 1.2.0
            - name: Install dependencies
              run: poetry install
            - name: Run my script
            run: |
                poetry run python build.py



