name: Deploy modules to dev
on:
  push:
    branches:
      - main
jobs:
  build-modules:
    runs-on: ubuntu-latest
    environment: dev
    env:
        CDF_CLUSTER: ${{ secrets.CDF_CLUSTER }}
        CDF_PROJECT: ${{ secrets.CDF_PROJECT }}
        IDP_CLIENT_ID: ${{ secrets.IDP_CLIENT_ID }}
        IDP_CLIENT_SECRET: ${{ secrets.IDP_CLIENT_SECRET }}
        IDP_TOKEN_URL: ${{ secrets.IDP_TOKEN_URL }}
    name: Loadmaster
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry install
      - name: "Pre-processing for demo environment"
        run: |
          ./demo/preproc.sh
      - name: "Build the package"
        run: |
          poetry run python cdf.py build --env=demo
      # be careful, this works as promised
      - name: "Delete existing resources including data"
        run: |
          poetry run python cdf.py clean --env=demo
      - name: "Deploy the package"
        run: |
          poetry run python cdf.py deploy --env=demo
      - name: "Run transformations and other post-processing"
        run: |
          poetry run python ./demo/postproc.py